table Fact_Ventas
	lineageTag: 8829407f-a967-4567-a87d-2472b0ba2540

	column FECHA_VENTA
		dataType: int64
		formatString: 0
		lineageTag: b37e01bf-23ba-4e55-aa14-e4d0ab542dc1
		summarizeBy: none
		sourceColumn: FECHA_VENTA

		annotation SummarizationSetBy = Automatic

	column COD_ARTICULO
		dataType: int64
		formatString: 0
		lineageTag: 20e2dcf3-81d1-4025-a3d6-873eb1c8c109
		summarizeBy: none
		sourceColumn: COD_ARTICULO

		annotation SummarizationSetBy = Automatic

	column CANT_VENDIDA
		dataType: int64
		formatString: 0
		lineageTag: 034cd0be-4be7-4e23-a4f9-2eebd11150f3
		summarizeBy: sum
		sourceColumn: CANT_VENDIDA

		annotation SummarizationSetBy = Automatic

	partition Fact_Ventas = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\aalonso\Fact_Ventas.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"FECHA_VENTA", Int64.Type}, {"COD_ARTICULO", Int64.Type}, {"CANT_VENDIDA", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

